repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0  # Make sure this is a valid version tag (check repository releases)
    hooks:
      - id: black # Code formater
        name: black
        entry: black --line-length=79
        language: python
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0  # Make sure this is a valid version tag (check repository releases)
    hooks:
      - id: flake8 # Linter
        name: flake8
        entry: flake8
        language: python
        types: [python]

